version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: arn:aws:ecs:us-east-1:594276799913:task-definition/backend-img:3
        LoadBalancerInfo:
          ContainerName: "server"
          ContainerPort: 3001
TrafficRoutingConfig:
  Type: TimeBasedCanary
  TimeBasedCanary:
    CanaryPercentage: 10
    CanaryInterval: 1