version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: ${NODEJS_VERSION}

  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --no-include-email --region ${AWS_REGION})
      - REPOSITORY_URI=${ECR_REPO_URI}
      - CONTAINER_NAME=${CONTAINER_NAME}

  build:
    commands:
      - echo Build started on `date`
      - npm install
      - echo Building Docker image...
      - docker build -t $REPOSITORY_URI:$CODEBUILD_RESOLVED_SOURCE_VERSION . # Build your Docker image

  post_build:
    commands:
      - echo Build completed on `date`
      - docker push $REPOSITORY_URI:$CODEBUILD_RESOLVED_SOURCE_VERSION
      - echo Writing image definitions file...
      - printf '[{"name":"'$CONTAINER_NAME'","imageUri":"%s"}]' $REPOSITORY_URI:$CODEBUILD_RESOLVED_SOURCE_VERSION > imagedefinitions.json

artifacts:
  files: imagedefinitions.json
